version: '3.9'

services:
  # Main Neuros Application
  neuros-app:
    build:
      context: .
      dockerfile: Dockerfile.simple
    container_name: neuros-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    networks:
      - neuros-network

  # PostgreSQL for Agents & Analytics
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_DB=neuros_ai
      - POSTGRES_USER=neuros
      - POSTGRES_PASSWORD=neuros_secure_pass_2024
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - neuros-network

  # Redis for Task Queue
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - neuros-network

networks:
  neuros-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data: