version: '3.8'

services:
  # Main development instance
  dev-main:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - PORT=3000
      - NODE_ENV=development
    command: npm run dev
    networks:
      - supa-network

  # Testing instance 1
  dev-test1:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    volumes:
      - .:/app:ro  # Read-only for testing
      - /app/node_modules
      - /app/.next
    environment:
      - PORT=3000
      - NODE_ENV=development
    command: npm run dev
    networks:
      - supa-network

  # Testing instance 2
  dev-test2:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3002:3000"
    volumes:
      - .:/app:ro  # Read-only for testing
      - /app/node_modules
      - /app/.next
    environment:
      - PORT=3000
      - NODE_ENV=development
    command: npm run dev
    networks:
      - supa-network

networks:
  supa-network:
    driver: bridge